name: Release
on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest]
        target: [aarch64-apple-darwin, x86_64-apple-darwin]
    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-20.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf

      - name: Install frontend dependencies
        run: npm install

      - name: Generate icons
        run: npm run generate-icons

      - name: Build the app
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: --target ${{ matrix.target }}
          tagName: ${{ github.ref_name }}
          releaseName: 'TypeTidy v${{ github.ref_name }}'
          releaseBody: 'See the assets to download and install this version.'
          releaseDraft: true
          prerelease: false

      - name: Sign App Bundle
        if: matrix.platform == 'macos-latest'
        run: |
          APP_PATH="src-tauri/target/${{ matrix.target }}/release/bundle/macos/TypeTidy.app"
          # Create an ad-hoc signature
          codesign --force --deep --sign - --timestamp "$APP_PATH"
          # Also sign the DMG
          DMG_PATH="src-tauri/target/${{ matrix.target }}/release/bundle/dmg/TypeTidy_${{ github.ref_name }}_${{ matrix.target }}.dmg"
          codesign --force --sign - --timestamp "$DMG_PATH"
          echo "✓ Signed app bundle and DMG with ad-hoc signature"
